spring:
    data:
        mongodb:
            username: myclover
            password:
            host: localhost
            port: 27017
            database: ms-customer
            authentication-database: admin
server:
    port: 8090