spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ms-product
    username: postgres
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    ignorePendingMigrations: true
    ignoreMissingMigrations: true
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: postgres
    password:
server:
  port: 8050